### ISSUE TITLE
Set up fission-publish with domain

### ISSUE THREAD

**Issue by bmann** [IPFSConnect/istanbul2023#1]
- [x] setup account ipfsconnect and app istanbul2023
- [x] setup keys for ipfsconnect in github
- [x] setup publishing action fission-publish
- [x] connect istanbul2023.ipfsconnect.org to fission dns

**Comment by bmann** [comment]
@avivash @walkah can I ask you two to set up fission app / publishing for this please

**Comment by avivash** [comment]
@bmann @walkah I've completed the first three items. the `FISSION_MACHINE_KEY` has been uploaded to this repo and i've setup the publish workflow. I've saved the key file to `ipfsconnect fission account` in 1pass, along with the base64 encoded version and the associated email

I haven't tested yet, but we may need someone at the org level to flip the switch for workflow write permissions.

https://istanbul2023.fission.app/

**Comment by avivash** [comment]
Just tested the publish workflow, looks like we will need someone with org-level admin access to flip [this switch](https://github.com/fission-codes/publish-action#403-resource-not-accessible-by-integration-github-api-error)

<img width="1314" alt="image" src="https://github.com/IPFSConnect/istanbul2023/assets/1179291/34aed63f-0de4-4af8-a04c-27b591ac6ab5">

**Comment by bmann** [comment]
@avivash thank you, flipped the switch!

@forgondolin can you please point istanbul2023.ipfsconnect.org -> https://istanbul2023.fission.app and then we're done.

@heybeckyv you can edit the HTML in this repo directly and the changes will get deployed automatically. Definitely still needs design work, but just good for you to test.

**Comment by walkah** [comment]
This is done.
