### ISSUE TITLE
Update Links on Homepage

### ISSUE THREAD

**Issue by heybeckyv** [IPFSConnect/istanbul2023#11]
Please remove the CFP CTA on the homepage. 

Please add the Workshop Signup button under the speakers section and include this link: https://docs.google.com/forms/d/e/1FAIpQLSfo2-rVPRUnecKBBblhA04dkVJoKNAprpXNcUO6mfu0EIcH_Q/viewform

**Comment by chadkoh** [comment]
Replaced the CFP button with a Workshop signup button
