### ISSUE TITLE
Add links to socials

### ISSUE THREAD

**Issue by bmann** [IPFSConnect/istanbul2023#4]
Let's get all of our social channels linked on the website.

I think we should just go with the IPFS Discord as the "conference" chat.

@heybeckyv can you list all the social accounts in this issues and a non-expiring link to the IPFS Discord.

**Comment by heybeckyv** [comment]
Mastodon: https://plnetwork.xyz/@ipfsconnect
Twitter: https://twitter.com/IPFSConnect
Fission Discord (non-expiring): https://discord.gg/fissioncodes

**Comment by heybeckyv** [comment]
Please add the Mastodon and Twitter social links above, and instead of the Fission Discord, please add this IPFS Discord invite link: https://discord.gg/ipfs
