### ISSUE TITLE
Add Clave logo under Media Partners

### ISSUE THREAD

**Issue by heybeckyv** [IPFSConnect/istanbul2023#7]
Please add the included logo
![clave](https://github.com/IPFSConnect/istanbul2023/assets/68623172/1222d049-db93-4104-99c4-3b7348a1e36a)

**Comment by heybeckyv** [comment]
This logo was accidentally deleted from the website. Please add it back. Thank you!

**Comment by depatchedmode** [comment]
Looks like it was accidentally removed in 2abc50799b2c588b4ca47db30acdf6da3784d206.

Will re-add.

**Comment by depatchedmode** [comment]
Fixed in aa8b218c7c35baba060b398f6ccd2e53676c0495 and deployed as of e005c99fb735c79fb09f007b0649eba2d9efa616
