### ISSUE TITLE
Please add sponsor logos

### ISSUE THREAD

**Issue by heybeckyv** [IPFSConnect/istanbul2023#8]
Please add the [attached sponsor logos](https://drive.google.com/drive/folders/10p2_k0Htjzvgi56dKt0y2-2_nwuod7eD?usp=drive_link) for SheFi and DataverseOS. SheFi is a Media sponsor, and DataverseOS is the Lunch sponsor.

**Comment by depatchedmode** [comment]
This is up now. Lmk what you think.

**Comment by heybeckyv** [comment]
Please create a Maintainer Level header and add the Tableland Logo to it.

**Comment by heybeckyv** [comment]
Please add web3.storage to the Maintainer level. Logo is in the folder (linked above).

**Comment by heybeckyv** [comment]
Please add ZuSocial Hacker House to the Media Sponsor level. Logo is in the folder (linked above).

**Comment by depatchedmode** [comment]
Completed in 17b32df6711c6307ef7e7746fda8c3c08324e94e

**Comment by heybeckyv** [comment]
Please add the Meta Era logo (located in GDrive) to the Media Sponsors level.

**Comment by heybeckyv** [comment]
Please add Saturn logo under Maintainer level.

**Comment by heybeckyv** [comment]
Please add number0 to the Maintainer Level.

**Comment by heybeckyv** [comment]
Please add Fenbushi to the Maintainer Level.
